const pool = require("../config/db");

const {
  notifyNewCustomer,
  emitCreatedAdminNotification,
} = require("../utils/adminNotificationEvents");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const crypto = require("crypto");

/* =========================================================
   VALIDATION / NORMALIZATION HELPERS
========================================================= */

const normalizeEmail = (email) => {
  return String(email || "").trim().toLowerCase();
};

const normalizePhone = (phone) => {
  return String(phone || "")
    .trim()
    .replace(/[\s()-]/g, "");
};

const normalizeName = (name) => {
  return String(name || "").trim().replace(/\s+/g, " ");
};

const isValidEmail = (email) => {
  const value = normalizeEmail(email);

  if (!value || value.length > 254) {
    return false;
  }

  const emailRegex =
    /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

  return emailRegex.test(value);
};

const isValidPhone = (phone) => {
  const value = normalizePhone(phone);

  /*
    Accepts:
    9876543210
    +919876543210

    Allows 8-15 digits according to international-style
    phone number length.
  */
  const phoneRegex =
    /^\+?[1-9]\d{7,14}$/;

  return phoneRegex.test(value);
};

const isValidPassword = (password) => {
  if (typeof password !== "string") {
    return false;
  }

  if (password.length < 8) {
    return false;
  }

  if (password.length > 128) {
    return false;
  }

  /*
    Password must contain:
    - uppercase
    - lowercase
    - number
  */
  return (
    /[A-Z]/.test(password) &&
    /[a-z]/.test(password) &&
    /[0-9]/.test(password)
  );
};

const isValidName = (name, required = false) => {
  if (typeof name !== "string") {
    return false;
  }

  const value = normalizeName(name);

  if (!value && !required) {
    return true;
  }

  if (value.length < 2 || value.length > 50) {
    return false;
  }

  /*
    Supports normal names including:
    John
    Mary Jane
    O'Connor
    Jean-Pierre
    Unicode names
  */
  const nameRegex =
    /^[\p{L}][\p{L}' -]*$/u;

  return nameRegex.test(value);
};

const isValidResetToken = (token) => {
  if (typeof token !== "string") {
    return false;
  }

  /*
    Tokens generated by crypto.randomBytes(32).toString("hex")
    contain exactly 64 hexadecimal characters.
  */
  return /^[a-f0-9]{64}$/i.test(token);
};

/* =========================================================
   REGISTER CUSTOMER
========================================================= */

const registerCustomer = async (req, res) => {
  try {
    const body = req.body || {};

    const {
      first_name,
      last_name,
      email,
      phone,
      password,
    } = body;

    /* =====================================================
       REQUIRED FIELD VALIDATION
    ===================================================== */

    if (
      first_name === undefined ||
      email === undefined ||
      phone === undefined ||
      password === undefined
    ) {
      return res.status(400).json({
        success: false,
        message:
          "First name, email, phone number and password are required",
      });
    }

    /* =====================================================
       NAME VALIDATION
    ===================================================== */

    if (!isValidName(first_name, true)) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid first name",
      });
    }

    if (
      last_name !== undefined &&
      last_name !== null &&
      last_name !== "" &&
      !isValidName(last_name, false)
    ) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid last name",
      });
    }

    /* =====================================================
       EMAIL VALIDATION
    ===================================================== */

    if (!isValidEmail(email)) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid email address",
      });
    }

    /* =====================================================
       PHONE VALIDATION
    ===================================================== */

    if (!isValidPhone(phone)) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid phone number",
      });
    }

    /* =====================================================
       PASSWORD VALIDATION
    ===================================================== */

    if (!isValidPassword(password)) {
      return res.status(400).json({
        success: false,
        message:
          "Password must be 8-128 characters and contain at least one uppercase letter, one lowercase letter and one number",
      });
    }

    /* =====================================================
       NORMALIZE DATA
    ===================================================== */

    const normalizedFirstName =
      normalizeName(first_name);

    const normalizedLastName =
      last_name
        ? normalizeName(last_name)
        : null;

    const normalizedEmail =
      normalizeEmail(email);

    const normalizedPhone =
      normalizePhone(phone);

    /* =====================================================
       CHECK DUPLICATE EMAIL
    ===================================================== */

    const existingEmail = await pool.query(
      `
      SELECT id
      FROM customers
      WHERE LOWER(email) = $1
      LIMIT 1
      `,
      [normalizedEmail]
    );

    if (existingEmail.rows.length > 0) {
      return res.status(409).json({
        success: false,
        message:
          "An account with this email already exists",
      });
    }

    /* =====================================================
       CHECK DUPLICATE PHONE
    ===================================================== */

    const existingPhone = await pool.query(
      `
      SELECT id
      FROM customers
      WHERE phone = $1
      LIMIT 1
      `,
      [normalizedPhone]
    );

    if (existingPhone.rows.length > 0) {
      return res.status(409).json({
        success: false,
        message:
          "An account with this phone number already exists",
      });
    }

    /* =====================================================
       HASH PASSWORD
    ===================================================== */

    const passwordHash =
      await bcrypt.hash(password, 12);

    /* =====================================================
       CREATE CUSTOMER
    ===================================================== */

    const result = await pool.query(
      `
      INSERT INTO customers (
        first_name,
        last_name,
        email,
        phone,
        password_hash
      )
      VALUES ($1, $2, $3, $4, $5)
      RETURNING
        id,
        first_name,
        last_name,
        email,
        phone,
        is_active,
        created_at
      `,
      [
        normalizedFirstName,
        normalizedLastName,
        normalizedEmail,
        normalizedPhone,
        passwordHash,
      ]
    );

    const customer = result.rows[0];

    // Admin notification (must never break registration)
    try {
      const adminNotification = await notifyNewCustomer(pool, {
        customerId: customer.id,
        customerName: [customer.first_name, customer.last_name]
          .filter(Boolean)
          .join(" "),
        email: customer.email,
      });

      emitCreatedAdminNotification(adminNotification);
    } catch (notificationError) {
      console.error(
        "New customer admin notification error:",
        notificationError
      );
    }

    return res.status(201).json({
      success: true,
      message:
        "Customer account created successfully",
      customer,
    });
  } catch (error) {
    console.error(
      "Registration error:",
      error
    );

    /* =====================================================
       HANDLE UNIQUE CONSTRAINT
    ===================================================== */

    if (error.code === "23505") {
      const constraint =
        error.constraint || "";

      if (
        constraint
          .toLowerCase()
          .includes("phone")
      ) {
        return res.status(409).json({
          success: false,
          message:
            "An account with this phone number already exists",
        });
      }

      if (
        constraint
          .toLowerCase()
          .includes("email")
      ) {
        return res.status(409).json({
          success: false,
          message:
            "An account with this email already exists",
        });
      }

      return res.status(409).json({
        success: false,
        message:
          "An account with these details already exists",
      });
    }

    return res.status(500).json({
      success: false,
      message:
        "Failed to create customer account",
    });
  }
};

/* =========================================================
   LOGIN CUSTOMER
========================================================= */

const loginCustomer = async (req, res) => {
  try {
    const body = req.body || {};

    const {
      email,
      password,
    } = body;

    /* =====================================================
       REQUIRED VALIDATION
    ===================================================== */

    if (
      email === undefined ||
      password === undefined
    ) {
      return res.status(400).json({
        success: false,
        message:
          "Email and password are required",
      });
    }

    if (!isValidEmail(email)) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid email address",
      });
    }

    if (
      typeof password !== "string" ||
      password.length === 0 ||
      password.length > 128
    ) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid password",
      });
    }

    const normalizedEmail =
      normalizeEmail(email);

    /* =====================================================
       FIND CUSTOMER
    ===================================================== */

    const result = await pool.query(
      `
      SELECT
        id,
        first_name,
        last_name,
        email,
        phone,
        password_hash,
        is_active
      FROM customers
      WHERE LOWER(email) = $1
      LIMIT 1
      `,
      [normalizedEmail]
    );

    /*
      Generic response prevents revealing whether
      an email/account exists.
    */

    if (result.rows.length === 0) {
      return res.status(401).json({
        success: false,
        message:
          "Invalid email or password",
      });
    }

    const customer = result.rows[0];

    /* =====================================================
       PASSWORD CHECK
    ===================================================== */

    const isPasswordValid =
      await bcrypt.compare(
        password,
        customer.password_hash
      );

    if (!isPasswordValid) {
      return res.status(401).json({
        success: false,
        message:
          "Invalid email or password",
      });
    }

    /* =====================================================
       ACCOUNT STATUS
    ===================================================== */

    if (!customer.is_active) {
      /*
        Keep the response generic instead of telling
        attackers that the account exists but is inactive.
      */
      return res.status(401).json({
        success: false,
        message:
          "Invalid email or password",
      });
    }

    /* =====================================================
       CHECK JWT SECRET
    ===================================================== */

    if (!process.env.JWT_SECRET) {
      console.error(
        "JWT_SECRET is not configured"
      );

      return res.status(500).json({
        success: false,
        message:
          "Authentication service is not configured",
      });
    }

    /* =====================================================
       CREATE JWT
    ===================================================== */

    const token = jwt.sign(
      {
        id: customer.id,
        email: customer.email,
      },
      process.env.JWT_SECRET,
      {
        expiresIn: "7d",
      }
    );

    /* =====================================================
       UPDATE LAST LOGIN
    ===================================================== */

    await pool.query(
      `
      UPDATE customers
      SET last_login_at = CURRENT_TIMESTAMP
      WHERE id = $1
      `,
      [customer.id]
    );

    /* =====================================================
       REMOVE PASSWORD HASH
    ===================================================== */

    delete customer.password_hash;

    /* =====================================================
       RESPONSE
    ===================================================== */

    return res.json({
      success: true,
      message: "Login successful",
      token,
      customer,
    });
  } catch (error) {
    console.error(
      "Login error:",
      error
    );

    return res.status(500).json({
      success: false,
      message: "Login failed",
    });
  }
};

/* =========================================================
   GET CURRENT CUSTOMER ACCOUNT
========================================================= */

const getCurrentCustomer = async (
  req,
  res
) => {
  try {
    const customerId =
      req.customer &&
      req.customer.id;

    if (!customerId) {
      return res.status(401).json({
        success: false,
        message:
          "Invalid authentication token",
      });
    }

    /* =====================================================
       GET CUSTOMER
    ===================================================== */

    const customerResult =
      await pool.query(
        `
        SELECT
          id,
          first_name,
          last_name,
          email,
          phone,
          profile_image_url,
          is_active,
          created_at
        FROM customers
        WHERE id = $1
        LIMIT 1
        `,
        [customerId]
      );

    if (
      customerResult.rows.length === 0
    ) {
      return res.status(404).json({
        success: false,
        message:
          "Customer account not found",
      });
    }

    const customer =
      customerResult.rows[0];

    if (!customer.is_active) {
      return res.status(403).json({
        success: false,
        message:
          "Customer account is inactive",
      });
    }

    /* =====================================================
       ORDER COUNT
    ===================================================== */

    const orderCountResult =
      await pool.query(
        `
        SELECT COUNT(*) AS count
        FROM orders
        WHERE customer_id = $1
        `,
        [customerId]
      );

    /* =====================================================
       ADDRESS COUNT
    ===================================================== */

    const addressCountResult =
      await pool.query(
        `
        SELECT COUNT(*) AS count
        FROM customer_addresses
        WHERE customer_id = $1
        `,
        [customerId]
      );

    /* =====================================================
       WISHLIST COUNT
    ===================================================== */

    const wishlistCountResult =
      await pool.query(
        `
        SELECT COUNT(*) AS count
        FROM wishlists
        WHERE customer_id = $1
        `,
        [customerId]
      );

    /* =====================================================
       RESPONSE
    ===================================================== */

    return res.json({
      success: true,

      customer: {
        id: customer.id,
        first_name:
          customer.first_name,
        last_name:
          customer.last_name || "",
        email: customer.email,
        phone: customer.phone,
        profile_image_url:
          customer.profile_image_url ||
          null,
        is_active:
          customer.is_active,
        created_at:
          customer.created_at,
      },

      summary: {
        orders: Number(
          orderCountResult.rows[0].count
        ),

        addresses: Number(
          addressCountResult.rows[0].count
        ),

        wishlist: Number(
          wishlistCountResult.rows[0].count
        ),
      },
    });
  } catch (error) {
    console.error(
      "Get current customer error:",
      error
    );

    return res.status(500).json({
      success: false,
      message:
        "Failed to load customer account",
    });
  }
};

/* =========================================================
   UPDATE CUSTOMER PROFILE
========================================================= */

const updateCustomerProfile = async (
  req,
  res
) => {
  try {
    const customerId =
      req.customer &&
      req.customer.id;

    if (!customerId) {
      return res.status(401).json({
        success: false,
        message:
          "Invalid authentication token",
      });
    }

    const body = req.body || {};

    const {
      first_name,
      last_name,
      email,
      phone,
    } = body;

    /* =====================================================
       REQUIRED VALIDATION
    ===================================================== */

    if (
      first_name === undefined ||
      email === undefined ||
      phone === undefined
    ) {
      return res.status(400).json({
        success: false,
        message:
          "First name, email and phone number are required",
      });
    }

    /* =====================================================
       VALIDATE NAME
    ===================================================== */

    if (!isValidName(first_name, true)) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid first name",
      });
    }

    if (
      last_name !== undefined &&
      last_name !== null &&
      last_name !== "" &&
      !isValidName(last_name, false)
    ) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid last name",
      });
    }

    /* =====================================================
       VALIDATE EMAIL
    ===================================================== */

    if (!isValidEmail(email)) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid email address",
      });
    }

    /* =====================================================
       VALIDATE PHONE
    ===================================================== */

    if (!isValidPhone(phone)) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid phone number",
      });
    }

    /* =====================================================
       NORMALIZE DATA
    ===================================================== */

    const normalizedFirstName =
      normalizeName(first_name);

    const normalizedLastName =
      last_name
        ? normalizeName(last_name)
        : null;

    const normalizedEmail =
      normalizeEmail(email);

    const normalizedPhone =
      normalizePhone(phone);

    /* =====================================================
       CHECK EMAIL
    ===================================================== */

    const existingEmail =
      await pool.query(
        `
        SELECT id
        FROM customers
        WHERE LOWER(email) = $1
          AND id <> $2
        LIMIT 1
        `,
        [
          normalizedEmail,
          customerId,
        ]
      );

    if (
      existingEmail.rows.length > 0
    ) {
      return res.status(409).json({
        success: false,
        message:
          "Another account already uses this email address",
      });
    }

    /* =====================================================
       CHECK PHONE
    ===================================================== */

    const existingPhone =
      await pool.query(
        `
        SELECT id
        FROM customers
        WHERE phone = $1
          AND id <> $2
        LIMIT 1
        `,
        [
          normalizedPhone,
          customerId,
        ]
      );

    if (
      existingPhone.rows.length > 0
    ) {
      return res.status(409).json({
        success: false,
        message:
          "Another account already uses this phone number",
      });
    }

    /* =====================================================
       UPDATE CUSTOMER
    ===================================================== */

    const result = await pool.query(
      `
      UPDATE customers
      SET
        first_name = $1,
        last_name = $2,
        email = $3,
        phone = $4,
        updated_at = CURRENT_TIMESTAMP
      WHERE id = $5
      RETURNING
        id,
        first_name,
        last_name,
        email,
        phone,
        profile_image_url,
        is_active,
        created_at,
        updated_at
      `,
      [
        normalizedFirstName,
        normalizedLastName,
        normalizedEmail,
        normalizedPhone,
        customerId,
      ]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({
        success: false,
        message:
          "Customer account not found",
      });
    }

    const customer =
      result.rows[0];

    return res.json({
      success: true,
      message:
        "Profile updated successfully",
      customer,
    });
  } catch (error) {
    console.error(
      "Update customer profile error:",
      error
    );

    /* =====================================================
       HANDLE UNIQUE CONSTRAINT
    ===================================================== */

    if (error.code === "23505") {
      const constraint =
        error.constraint || "";

      if (
        constraint
          .toLowerCase()
          .includes("phone")
      ) {
        return res.status(409).json({
          success: false,
          message:
            "Another account already uses this phone number",
        });
      }

      if (
        constraint
          .toLowerCase()
          .includes("email")
      ) {
        return res.status(409).json({
          success: false,
          message:
            "Another account already uses this email address",
        });
      }
    }

    return res.status(500).json({
      success: false,
      message:
        "Failed to update profile",
    });
  }
};

/* =========================================================
   FORGOT PASSWORD
========================================================= */

const forgotPassword = async (
  req,
  res
) => {
  try {
    const body = req.body || {};

    const { email } = body;

    /* =====================================================
       VALIDATE EMAIL
    ===================================================== */

    if (email === undefined) {
      return res.status(400).json({
        success: false,
        message:
          "Email address is required",
      });
    }

    if (!isValidEmail(email)) {
      return res.status(400).json({
        success: false,
        message:
          "Please enter a valid email address",
      });
    }

    const normalizedEmail =
      normalizeEmail(email);

    /* =====================================================
       FIND CUSTOMER
    ===================================================== */

    const customerResult =
      await pool.query(
        `
        SELECT
          id,
          email,
          is_active
        FROM customers
        WHERE LOWER(email) = $1
        LIMIT 1
        `,
        [normalizedEmail]
      );

    /*
      IMPORTANT:
      Do not reveal whether an account exists.
    */

    const genericResponse = {
      success: true,
      message:
        "If an account exists with this email, a password reset link has been generated.",
    };

    if (
      customerResult.rows.length === 0
    ) {
      return res.json(
        genericResponse
      );
    }

    const customer =
      customerResult.rows[0];

    /* =====================================================
       INACTIVE ACCOUNT
    ===================================================== */

    if (!customer.is_active) {
      return res.json(
        genericResponse
      );
    }

    /* =====================================================
       INVALIDATE OLD TOKENS
    ===================================================== */

    await pool.query(
      `
      UPDATE password_reset_tokens
      SET used_at = CURRENT_TIMESTAMP
      WHERE customer_id = $1
        AND used_at IS NULL
      `,
      [customer.id]
    );

    /* =====================================================
       GENERATE SECURE TOKEN
    ===================================================== */

    const resetToken =
      crypto
        .randomBytes(32)
        .toString("hex");

    /* =====================================================
       HASH TOKEN BEFORE DATABASE STORAGE
    ===================================================== */

    const tokenHash =
      crypto
        .createHash("sha256")
        .update(resetToken)
        .digest("hex");

    /* =====================================================
       TOKEN EXPIRATION
    ===================================================== */

    const expiresAt = new Date(
      Date.now() +
        30 * 60 * 1000
    );

    /* =====================================================
       SAVE TOKEN
    ===================================================== */

    await pool.query(
      `
      INSERT INTO password_reset_tokens (
        customer_id,
        token_hash,
        expires_at
      )
      VALUES ($1, $2, $3)
      `,
      [
        customer.id,
        tokenHash,
        expiresAt,
      ]
    );

    /* =====================================================
       DEVELOPMENT RESET URL
    ===================================================== */

    const frontendUrl =
      process.env.FRONTEND_URL ||
      "http://localhost:5173";

    const resetUrl =
      `${frontendUrl}/reset-password?token=${resetToken}`;

    /*
      Development only.

      Later replace this with an actual email service.
    */

    console.log(
      "\n=========================================="
    );

    console.log(
      "PASSWORD RESET REQUEST"
    );

    console.log(
      "Customer:",
      customer.email
    );

    console.log(
      "Reset URL:"
    );

    console.log(resetUrl);

    console.log(
      "==========================================\n"
    );

    return res.json({
      ...genericResponse,

      /*
        Keep this only while developing.
        Remove before production.
      */
      developmentResetUrl:
        resetUrl,
    });
  } catch (error) {
    console.error(
      "Forgot password error:",
      error
    );

    return res.status(500).json({
      success: false,
      message:
        "Unable to process password reset request",
    });
  }
};

/* =========================================================
   RESET PASSWORD
========================================================= */

const resetPassword = async (
  req,
  res
) => {
  let client;

  try {
    const body = req.body || {};

    const {
      token,
      password,
      confirm_password,
    } = body;

    /* =====================================================
       REQUIRED VALIDATION
    ===================================================== */

    if (
      token === undefined ||
      password === undefined ||
      confirm_password === undefined
    ) {
      return res.status(400).json({
        success: false,
        message:
          "Reset token, password and confirm password are required",
      });
    }

    /* =====================================================
       TOKEN VALIDATION
    ===================================================== */

    if (!isValidResetToken(token)) {
      return res.status(400).json({
        success: false,
        message:
          "Invalid or expired password reset link",
      });
    }

    /* =====================================================
       PASSWORD VALIDATION
    ===================================================== */

    if (!isValidPassword(password)) {
      return res.status(400).json({
        success: false,
        message:
          "Password must be 8-128 characters and contain at least one uppercase letter, one lowercase letter and one number",
      });
    }

    /* =====================================================
       CONFIRM PASSWORD
    ===================================================== */

    if (password !== confirm_password) {
      return res.status(400).json({
        success: false,
        message:
          "Passwords do not match",
      });
    }

    /* =====================================================
       HASH RESET TOKEN
    ===================================================== */

    const tokenHash =
      crypto
        .createHash("sha256")
        .update(token)
        .digest("hex");

    /* =====================================================
       GET DATABASE CLIENT
    ===================================================== */

    client = await pool.connect();

    await client.query("BEGIN");

    /* =====================================================
       FIND RESET TOKEN
    ===================================================== */

    const tokenResult =
      await client.query(
        `
        SELECT
          id,
          customer_id,
          expires_at,
          used_at
        FROM password_reset_tokens
        WHERE token_hash = $1
        LIMIT 1
        FOR UPDATE
        `,
        [tokenHash]
      );

    if (
      tokenResult.rows.length === 0
    ) {
      await client.query("ROLLBACK");

      return res.status(400).json({
        success: false,
        message:
          "Invalid or expired password reset link",
      });
    }

    const resetRecord =
      tokenResult.rows[0];

    /* =====================================================
       CHECK TOKEN USED
    ===================================================== */

    if (resetRecord.used_at) {
      await client.query("ROLLBACK");

      return res.status(400).json({
        success: false,
        message:
          "This password reset link has already been used",
      });
    }

    /* =====================================================
       CHECK TOKEN EXPIRATION
    ===================================================== */

    if (
      new Date(resetRecord.expires_at) <=
      new Date()
    ) {
      await client.query("ROLLBACK");

      return res.status(400).json({
        success: false,
        message:
          "This password reset link has expired",
      });
    }

    /* =====================================================
       FIND CUSTOMER
    ===================================================== */

    const customerResult =
      await client.query(
        `
        SELECT
          id,
          is_active
        FROM customers
        WHERE id = $1
        LIMIT 1
        FOR UPDATE
        `,
        [resetRecord.customer_id]
      );

    if (
      customerResult.rows.length === 0
    ) {
      await client.query("ROLLBACK");

      return res.status(404).json({
        success: false,
        message:
          "Customer account not found",
      });
    }

    const customer =
      customerResult.rows[0];

    /* =====================================================
       CHECK ACCOUNT STATUS
    ===================================================== */

    if (!customer.is_active) {
      await client.query("ROLLBACK");

      return res.status(403).json({
        success: false,
        message:
          "Customer account is inactive",
      });
    }

    /* =====================================================
       HASH NEW PASSWORD
    ===================================================== */

    const passwordHash =
      await bcrypt.hash(
        password,
        12
      );

    /* =====================================================
       UPDATE PASSWORD
    ===================================================== */

    await client.query(
      `
      UPDATE customers
      SET
        password_hash = $1,
        updated_at = CURRENT_TIMESTAMP
      WHERE id = $2
      `,
      [
        passwordHash,
        customer.id,
      ]
    );

    /* =====================================================
       MARK CURRENT TOKEN AS USED
    ===================================================== */

    await client.query(
      `
      UPDATE password_reset_tokens
      SET
        used_at = CURRENT_TIMESTAMP
      WHERE id = $1
      `,
      [resetRecord.id]
    );

    /* =====================================================
       INVALIDATE OTHER RESET TOKENS
    ===================================================== */

    await client.query(
      `
      UPDATE password_reset_tokens
      SET
        used_at = CURRENT_TIMESTAMP
      WHERE customer_id = $1
        AND id <> $2
        AND used_at IS NULL
      `,
      [
        customer.id,
        resetRecord.id,
      ]
    );

    /* =====================================================
       COMMIT
    ===================================================== */

    await client.query("COMMIT");

    return res.json({
      success: true,
      message:
        "Password has been reset successfully. You can now log in with your new password.",
    });
  } catch (error) {
    if (client) {
      try {
        await client.query(
          "ROLLBACK"
        );
      } catch (rollbackError) {
        console.error(
          "Rollback error:",
          rollbackError
        );
      }
    }

    console.error(
      "Reset password error:",
      error
    );

    return res.status(500).json({
      success: false,
      message:
        "Unable to reset password",
    });
  } finally {
    if (client) {
      client.release();
    }
  }
};

/* =========================================================
   EXPORTS
========================================================= */

module.exports = {
  registerCustomer,
  loginCustomer,
  getCurrentCustomer,
  updateCustomerProfile,
  forgotPassword,
  resetPassword,
};